- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get the entries count
  ansible.builtin.command:  mongo --host mongodb.daws76s.store --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: entries_count
  when: component == "catalogue"


- name: get the entries count
  ansible.builtin.command:  mongo --host mongodb.daws76s.store --quiet --eval 'db = db.getSiblingDB("catalogue"); db.user.count()'
  register: entries_count
  when: component == "user"





# - name: print the count
#   ansible.builtin.debug:
#     msg: "product count: {{product_count}}"

- name: load {{component}} data
  ansible.builtin.command: "mongo --host mongodb.daws76s.online < /app/schema/{{component}}.js"
  when: entries_count.stdout == "0" # keep double quotes

  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes