- name: Copy user service
  ansible.builtin.copy:
   src: user.service
   dest: /etc/systemd/system/user.service

- name: deamon reload and start
  ansible.builtin.systemd_service:
   daemon_reload: true   

- name: start and enable user
  ansible.builtin.service:
   name: user
   state: restarted
   enabled: yes